DROP TABLE IF EXISTS aire3;
 
CREATE TABLE aire3 (
      ID SERIAL,
      CODI_MUNICIPI INT,
      MUNICIPI VARCHAR,
      ESTACIO INT,
      CODI_CONTAMINANT INT,
      TEMPS TIMESTAMP,
      VALOR FLOAT
);
